name: Build and release

on:
  push:
    branches:
      - "!*"
    tags:
      - "v*"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set env
      run: echo "RELEASE_VERSION=$(echo ${GITHUB_REF:10})" >> $GITHUB_ENV
    - name: Build and generate artifact
      run: ./tools/release-deploy.sh
    - name: GH Release
      uses: softprops/action-gh-release@v0.1.13
      with:
        files: ./release/ED64P-${{ env.RELEASE_VERSION }}.zip

